### PR TITLE
feat: 🎸 set upvote downvote sorted, keeping upvote on top

### PR DESCRIPTION
**Pull request by varora1406**

### CODE REVIEW

**Comment by varora1406** [comment]
[Add sorting in seach results](https://trello.com/c/8Uo17UwU/86-add-sorting-in-seach-results)

**Comment by varora1406** [comment]
[Add sorting in seach results](https://trello.com/c/8Uo17UwU/86-add-sorting-in-seach-results)

**Comment by varora1406** [comment]
[Add sorting in seach results](https://trello.com/c/8Uo17UwU/86-add-sorting-in-seach-results)

**Review by ArpitBansal87 — APPROVED** [review]
👍

**Pull request merged**
